name: Build DashBoost iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build iOS
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: iOS

      - name: Upload DashBoost
        uses: actions/upload-artifact@v7
        with:
          name: DashBoost-iOS
          path: ${{ steps.build.outputs.build-output }}/*.geode
